# Generated by Django 5.2 on 2025-05-04 23:32

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_empresa_usuario_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='creation_date',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now),
        ),
    ]
