# Generated by Django 5.2 on 2025-05-25 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_certificate_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='system.empresa'),
        ),
    ]
