# Generated by Django 5.2 on 2025-05-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_certificate_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
