# Generated by Django 5.2 on 2025-06-30 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_usuario_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='middle_name',
        ),
    ]
